# Data Preprocessing

In [1]:
!pip install pandas

In [2]:
!pip install sklearn

In [3]:
# Import libaries
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
# Import dataset
dataset= pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
# Create feature matrix X and dependent vector Y
X= dataset.iloc[:,3:-1].values
Y= dataset.iloc[:,-1].values

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
# Encoding using LabelEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=np.array(le.fit_transform(X[:,2]))

In [8]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
# Encoding using OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [10]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [11]:
# Replacing missing data
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan,strategy='mean')
X= imputer.fit_transform(X)

In [12]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [13]:
# Spliting dataset into training and testing
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest= train_test_split(X,Y,test_size=0.2,random_state=1)

# Building Deep Learning Model

In [14]:
# Building a model
d1= tf.keras.models.Sequential()
# First hidden layer
d1.add(tf.keras.layers.Dense(units=1,activation='relu'))
# Second hidden layer
d1.add(tf.keras.layers.Dense(units=1,activation='relu'))
# Output layer
d1.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [15]:
# Compile the model
d1.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [16]:
# Training the model
d1.fit(Xtrain,Ytrain)

250/250 [==============================] - 0s 1ms/step - loss: 0.7680 - accuracy: 0.6463


In [17]:
d1.fit(Xtrain,Ytrain,epochs=400)

Epoch 1/400
250/250 [==============================] - 0s 1ms/step - loss: 0.6183 - accuracy: 0.7818
Epoch 2/400
250/250 [==============================] - 0s 1ms/step - loss: 0.5701 - accuracy: 0.8087
Epoch 3/400
250/250 [==============================] - 0s 2ms/step - loss: 0.5384 - accuracy: 0.8121
Epoch 4/400
250/250 [==============================] - 1s 3ms/step - loss: 0.5136 - accuracy: 0.8155
Epoch 5/400
250/250 [==============================] - 1s 3ms/step - loss: 0.4935 - accuracy: 0.8180
Epoch 6/400
250/250 [==============================] - 1s 3ms/step - loss: 0.4780 - accuracy: 0.8169
Epoch 7/400
250/250 [==============================] - 1s 3ms/step - loss: 0.4668 - accuracy: 0.8189
Epoch 8/400
250/250 [==============================] - 1s 2ms/step - loss: 0.4586 - accuracy: 0.8183
Epoch 9/400
250/250 [==============================] - 1s 2ms/step - loss: 0.4527 - accuracy: 0.8180
Epoch 10/400
250/250 [==============================] - 1s 2ms/step - loss: 0.4482 - accura

In [18]:
# Testing the model
Yest= d1.predict(Xtest)
Yest

array([[0.09569132],
       [0.15636042],
       [0.12047338],
       ...,
       [0.04224467],
       [0.12994447],
       [0.31388658]], dtype=float32)

In [19]:
Yest= (Yest>0.5)
Yest

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [21]:
# Encoding
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
Yest= le.fit_transform(Yest)
Yest

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Performance metrics

In [22]:
# Performance metrics
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score
cm= confusion_matrix(Ytest,Yest)
print('Confusion matrix : ')
print(cm)
print('Accuracy score: ',accuracy_score(Ytest,Yest))
print('Precision score: ',precision_score(Ytest,Yest))
print('Recall score: ',recall_score(Ytest,Yest))

Confusion matrix : 
[[1528   57]
 [ 321   94]]
Accuracy score:  0.811
Precision score:  0.6225165562913907
Recall score:  0.22650602409638554
