# Part A : Data Preprocessing

# import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# import dataset

In [2]:
dataset = pd.read_csv('Logistic Data.csv')

In [3]:
dataset

Age  Salary  Purchased Plot
0     22   22990               0
1     38   24200               0
2     29   52030               0
3     30   68970               0
4     22   91960               0
..   ...     ...             ...
395   49   49610               1
396   54   27830               1
397   53   24200               1
398   39   39930               0
399   52   43560               1

[400 rows x 3 columns]

# create feature matrix X and dependent vector Y

In [4]:
X= dataset.iloc[:,:-1].values
Y= dataset.iloc[:,-1].values

In [5]:
X

array([[    22,  22990],
       [    38,  24200],
       [    29,  52030],
       [    30,  68970],
       [    22,  91960],
       [    30,  70180],
       [    30, 101640],
       [    35, 181500],
       [    28,  39930],
       [    38,  78650],
       [    29,  96800],
       [    29,  62920],
       [    23, 104060],
       [    35,  21780],
       [    21,  99220],
       [    32,  96800],
       [    50,  30250],
       [    48,  31460],
       [    49,  33880],
       [    51,  35090],
       [    48,  26620],
       [    50,  59290],
       [    51,  49610],
       [    48,  26620],
       [    49,  27830],
       [    50,  24200],
       [    52,  33880],
       [    50,  36300],
       [    32,  52030],
       [    34,  21780],
       [    34,  89540],
       [    30, 165770],
       [    24,  19360],
       [    31,  53240],
       [    30, 108900],
       [    38,  32670],
       [    36,  33880],
       [    33,  59290],
       [    29,  87120],
       [    30,  37510],


In [6]:
Y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

# replacing missing data

In [7]:
from sklearn.impute import SimpleImputer

In [8]:
imputer= SimpleImputer(missing_values=np.nan,strategy='mean')
X= imputer.fit_transform(X)

In [9]:
X

array([[2.2000e+01, 2.2990e+04],
       [3.8000e+01, 2.4200e+04],
       [2.9000e+01, 5.2030e+04],
       [3.0000e+01, 6.8970e+04],
       [2.2000e+01, 9.1960e+04],
       [3.0000e+01, 7.0180e+04],
       [3.0000e+01, 1.0164e+05],
       [3.5000e+01, 1.8150e+05],
       [2.8000e+01, 3.9930e+04],
       [3.8000e+01, 7.8650e+04],
       [2.9000e+01, 9.6800e+04],
       [2.9000e+01, 6.2920e+04],
       [2.3000e+01, 1.0406e+05],
       [3.5000e+01, 2.1780e+04],
       [2.1000e+01, 9.9220e+04],
       [3.2000e+01, 9.6800e+04],
       [5.0000e+01, 3.0250e+04],
       [4.8000e+01, 3.1460e+04],
       [4.9000e+01, 3.3880e+04],
       [5.1000e+01, 3.5090e+04],
       [4.8000e+01, 2.6620e+04],
       [5.0000e+01, 5.9290e+04],
       [5.1000e+01, 4.9610e+04],
       [4.8000e+01, 2.6620e+04],
       [4.9000e+01, 2.7830e+04],
       [5.0000e+01, 2.4200e+04],
       [5.2000e+01, 3.3880e+04],
       [5.0000e+01, 3.6300e+04],
       [3.2000e+01, 5.2030e+04],
       [3.4000e+01, 2.1780e+04],
       [3.

# encoding not reqd

# Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc= StandardScaler()
X= sc.fit_transform(X)

In [12]:
X

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

# spliting the dataset into training and testing

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
Xtrain,Xtest,Ytrain,Ytest= train_test_split(X,Y,test_size=0.2,random_state=1)

# Part B : Building the Machine Learning model

# training the Logistic Regression model

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
lr= LogisticRegression(random_state=0)
lr.fit(Xtrain,Ytrain)

LogisticRegression(random_state=0)

# testing the model

In [17]:
Yestimated= lr.predict(Xtest)

In [18]:
Yestimated

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [19]:
Ytest

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [20]:
np.concatenate((Yestimated.reshape(len(Yestimated),1),Ytest.reshape(len(Ytest),1)),1)

array([[0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0,

# Part C : Performance Metric

In [21]:
# Confusion matrix : used to evaluate the performance of a classification model
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Ytest,Yestimated)
print('Confusion matrix : ')
print(cm)

Confusion matrix : 
[[41  7]
 [ 6 26]]


In [22]:
from sklearn.metrics import accuracy_score,precision_score
ac= accuracy_score(Ytest,Yestimated)
ps= precision_score(Ytest,Yestimated)
print('Accuracy score: ',ac)
print('Precision score: ',ps)

Accuracy score:  0.8375
Precision score:  0.7878787878787878
